// Here are the functions used in tinnyapp:

//  This function generates a tandom string for short URLS

function generateRandomString() {
  let alphaNumericString = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvxyz";
  let randomString = [];
  for (let i = 0; i < 6; i++) {
    randomString.push(alphaNumericString.charAt(Math.trunc(alphaNumericString.length * Math.random())));
  }
  return randomString.join('');
}

/// This function finds a user from email address in users database

const getUserByEmail = (email2, database) => {
  let myUsers = Object.entries(database);
  if (JSON.stringify(myUsers).includes(email2)) {
    let theUser = {};
    for (let i = 0; i < myUsers.length; i++) {
      if (myUsers[i][1].email === email2) {
        theUser = myUsers[i];
      }
    }
    return theUser;
  } else return null;
}

// This function finds the short URLS generated by a user with userId:

const urlForUser = (urlDatabase, userId) => {
  let myArr = {};
  let myVal = Object.keys(urlDatabase);
  for (let key of myVal) {
      if (urlDatabase[key].userID === userId) {
        myArr[key] = urlDatabase[key];
      };
  }
  return myArr;
}

// This function generate a random user ID:

const userIdGen = bank => {
  let id = Math.trunc(1000 * Math.random());
  bank.includes(id) ? id = userIdGen(bank) : bank.push(id);
  return id;
}

module.exports = { generateRandomString, getUserByEmail, urlForUser, userIdGen }